# Generated by Django 4.2.7 on 2023-12-05 22:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_alter_task_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="datetime",
            new_name="created_at",
        ),
    ]
