# Generated by Django 4.2.7 on 2023-12-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0003_rename_datetime_task_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="content",
            field=models.TextField(max_length=100),
        ),
    ]
